# Generated by Django 4.2.3 on 2024-04-15 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
        ('diets', '0002_remove_diet_recipe_diet_afternoon_meal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='afternoon_meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afternoon_meal_recipe', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='breakfast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_recipe', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dinner_recipe', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch_recipe', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='second_breakfast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_breakfast_recipe', to='recipe.recipe'),
        ),
    ]
