# Generated by Django 4.2.3 on 2024-04-15 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diets', '0003_alter_diet_afternoon_meal_alter_diet_breakfast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
