# Generated by Django 4.2.3 on 2024-06-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0005_diet_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='end_diet_date',
            field=models.DateField(auto_now=True, verbose_name='end_diet_date'),
        ),
        migrations.AddField(
            model_name='diet',
            name='start_diet_date',
            field=models.DateField(auto_now=True, verbose_name='start_diet_date'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default=('monday', 'Monday'), max_length=20, verbose_name='day'),
        ),
    ]
