# Generated by Django 4.2.3 on 2024-06-07 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0006_diet_end_diet_date_diet_start_diet_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='end_diet_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='end_diet_date'),
        ),
        migrations.AlterField(
            model_name='diet',
            name='start_diet_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='start_diet_date'),
        ),
    ]
