# Generated by Django 4.2.3 on 2024-06-09 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0007_alter_diet_end_diet_date_alter_diet_start_diet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='day'),
        ),
    ]
