# Generated by Django 4.2.3 on 2024-07-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0008_alter_diet_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='day',
            field=models.CharField(choices=[('1', 'Day 1'), ('2', 'Day 2'), ('3', 'Day 3'), ('4', 'Day 4'), ('5', 'Day 5'), ('6', 'Day 6'), ('7', 'Day 7')], max_length=12, verbose_name='day'),
        ),
    ]
