# Generated by Django 4.2.3 on 2023-08-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_calories_product_carbohydrates_product_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.PositiveIntegerField(default=0, help_text='calories per 100g', verbose_name='calories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.PositiveIntegerField(default=0, help_text='carbohydrates per 100g', verbose_name='carbohydrates'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.PositiveIntegerField(default=0, help_text='fat per 100g', verbose_name='fat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.PositiveIntegerField(default=0, help_text='protein per 100g', verbose_name='protein'),
        ),
    ]
