# Generated by Django 4.2.3 on 2023-08-08 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
        ('product', '0003_alter_product_calories_alter_product_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
        ),
    ]
